### ISSUE TITLE
CLA? Ownership of Code?

### ISSUE THREAD

**Issue by bketelsen** [gopheracademy/congo#7]
We will always make the app opensource.  But what if we decide to provide a hosted service to other conferences in the future?  What legal implications are there?  Decide now before we accept any contributions.

**Comment by ohohoreilly** [comment]
bketelsen I think a basic CLA would cover our needs to maintain maximum flexibility over the code.

**Comment by bketelsen** [comment]
Added CLAHub integration and liberal CLA assigning license to GopherAcademy.
